[package]
name = "pathvis-rs"
version = "0.1.0"
authors = ["Stuart Donnan <sdonnan@fastmail.com>"]

[dependencies]
piston = "0.37.0"
pistoncore-glutin_window = "0.47.0"
piston2d-graphics = "0.26.0"
piston2d-opengl_graphics = "0.53.0"
